using System;
using System.Collections.Generic;

#nullable disable

namespace Web_API_AIS_SN.SNModels
{
    public partial class AccountService3
    {
        public long Id { get; set; }
        public DateTime Period { get; set; }
        public long AccountServiceId { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public long? ApartmentId { get; set; }
        public string ApartmentNumber { get; set; }
        public long? AccountId { get; set; }
        public string AccountNumber { get; set; }
        public long? AccountOwnerId { get; set; }
        public string AccountOwnerName { get; set; }
        public DateTime? AccountFromDate { get; set; }
        public DateTime? AccountToDate { get; set; }
        public long ServiceId { get; set; }
        public int? ServiceCode { get; set; }
        public string ServiceName { get; set; }
        public long? ServiceTypeId { get; set; }
        public string ServiceTypeName { get; set; }
        public long? ServiceTariffId { get; set; }
        public decimal? ServiceTariffRate { get; set; }
        public long? ServiceNormId { get; set; }
        public decimal? ServiceNormValue { get; set; }
        public long? ProviderId { get; set; }
        public int? ProviderCode { get; set; }
        public string ProviderName { get; set; }
        public decimal? Balance { get; set; }
        public decimal? BalanceCount { get; set; }
        public decimal? CurrentCharge { get; set; }
        public decimal? ChargeBenefitCurrentMonth { get; set; }
        public decimal? Subsidy { get; set; }
        public decimal? CashPayment { get; set; }
        public decimal? CashReverse { get; set; }
        public decimal? CashlessPayment { get; set; }
        public decimal? CashlessReverse { get; set; }
        public decimal? CurrentChargeRecalc { get; set; }
        public decimal? RecalcChargeOldMonth { get; set; }
        public decimal? RecalcChargeFutureMonth { get; set; }
        public decimal? FinalRecalcCharge { get; set; }
        public decimal? RecalcChargeBenefitCurrentMonth { get; set; }
        public decimal? RecalcChargeBenefitOldMonth { get; set; }
        public decimal? RecalcChargeBenefitFutureMonth { get; set; }
        public decimal? FinalRecalcChargeBenefit { get; set; }
        public decimal? CancelChargeCurrentMonth { get; set; }
        public decimal? CancelChargeOldMonth { get; set; }
        public decimal? CancelChargeFutureMonth { get; set; }
        public decimal? CancelChargeBenefitCurrentMonth { get; set; }
        public decimal? CancelChargeBenefitOldMonth { get; set; }
        public decimal? CancelChargeBenefitFutureMonth { get; set; }
        public decimal? CancelPaymentCurrentMonth { get; set; }
        public decimal? CancelPaymentOldMonth { get; set; }
        public decimal? CancelPaymentFutureMonth { get; set; }
        public decimal? PaymentCurrentMonth { get; set; }
        public decimal? PaymentOldMonth { get; set; }
        public decimal? PaymentFutureMonth { get; set; }
        public decimal? IncDebtCurrentMonth { get; set; }
        public decimal? IncDebtOldMonth { get; set; }
        public decimal? IncDebtFutureMonth { get; set; }
        public decimal? DecDebtCurrentMonth { get; set; }
        public decimal? DecDebtOldMonth { get; set; }
        public decimal? DecDebtFutureMonth { get; set; }
        public decimal? BalanceBeg { get; set; }
        public decimal? BalanceEnd { get; set; }
        public decimal? PenaltyCharge { get; set; }
        public decimal? PenaltyPayment { get; set; }
        public decimal? BalanceDelta { get; set; }
        public decimal? FinalCashPayment { get; set; }
        public decimal? FinalCashlessPayment { get; set; }
        public decimal? FinalBuhPayment { get; set; }
        public decimal? FinalBuhCancelPayment { get; set; }
        public decimal? ActualPayment { get; set; }
        public decimal? PaymentPercent { get; set; }
        public decimal? InitialActualCharge { get; set; }
        public decimal? InitialActualRecalc { get; set; }
        public decimal? FinalCharge { get; set; }
        public decimal? FinalChargeBenefit { get; set; }
        public decimal? ActualCharge { get; set; }
        public int? CounterCount { get; set; }
        public decimal? Consumption { get; set; }
        public long? ResourceProviderId { get; set; }
        public long? ServiceHouseHolderId { get; set; }
        public long? ServiceAddrId { get; set; }
        public string ResourceProviderName { get; set; }
        public string ServiceHouseHolderName { get; set; }
        public string ServiceAddrName { get; set; }
        public long? CanonicalId { get; set; }
        public string CanonicalName { get; set; }
        public int? ResidentDaysCount { get; set; }
        public int? ResidentVacationDaysCount { get; set; }
        public long? AccountHouseHolderId { get; set; }
        public string AccountHouseHolderName { get; set; }
        public decimal? RecalcChargeCurrentMonthBySuspension { get; set; }
        public decimal? RecalcChargeOldMonthBySuspension { get; set; }
        public decimal? RecalcChargeFutureMonthBySuspension { get; set; }
        public int? CreatedResidentVacationDaysCount { get; set; }
        public decimal? ServiceTariffRateForResource { get; set; }
        public DateTime Created { get; set; }
        public decimal? SubsidyPayment { get; set; }
        public decimal? MonetizedBenefitPayment { get; set; }
        public DateTime? DateLastPayment { get; set; }
        public decimal? ChargeMonetizedBenefitCurrentMonth { get; set; }
        public decimal? RecalcChargeMonetizedBenefitCurrentMonth { get; set; }
        public decimal? RecalcChargeMonetizedBenefitOldMonth { get; set; }
        public decimal? RecalcChargeMonetizedBenefitFutureMonth { get; set; }
        public decimal? CancelChargeMonetizedBenefitCurrentMonth { get; set; }
        public decimal? CancelChargeMonetizedBenefitOldMonth { get; set; }
        public decimal? CancelChargeMonetizedBenefitFutureMonth { get; set; }
        public decimal? CancelDebtPaymentCurrentMonth { get; set; }
        public decimal? CancelDebtPaymentOldMonth { get; set; }
        public decimal? CancelDebtPaymentFutureMonth { get; set; }
        public decimal? DebtPaymentCurrentMonth { get; set; }
        public decimal? DebtPaymentOldMonth { get; set; }
        public decimal? DebtPaymentFutureMonth { get; set; }
        public decimal? TransferDebtCurrentMonth { get; set; }
        public decimal? TransferDebtOldMonth { get; set; }
        public decimal? TransferDebtFutureMonth { get; set; }
        public long? FinancialCenterId { get; set; }
        public bool? IsCounter { get; set; }
        public long? ServiceApartmentTypeId { get; set; }
        public string ServiceApartmentTypeName { get; set; }
        public long? AdministrationDistrictId { get; set; }
        public string AdministrationDistrictName { get; set; }
        public long? UserId { get; set; }
        public decimal? PenaltyBeg { get; set; }
        public decimal? PenaltyEnd { get; set; }
        public long? RemiteeOrganizationId { get; set; }
    }
}
